name: WatchDemo
options:
  bundleIdPrefix: com.xx.xx.sdk
  deploymentTarget:
    watchOS: "10.0"
  developmentLanguage: zh-Hans
settings:
  SWIFT_VERSION: "5.0"
  TARGETED_DEVICE_FAMILY: "4"
  CLANG_CXX_LANGUAGE_STANDARD: "c++17"
  CLANG_CXX_LIBRARY: "libc++"

targets:
  WatchDemo:
    type: application
    platform: watchOS
    sources:
      - path: Sources
    dependencies:
      # 蓝牙 Pod frameworks（直接使用）
      - framework: Frameworks/CryptoSwift.framework
        embed: true
      # OC 封装（给 miconnect C++ 用）
      - framework: Frameworks/xxMiWear.framework
        embed: true
      # c++ 的framework（依赖xxMiWear）
      - framework: Frameworks/aa.framework
        embed: true
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.xx.xx.sdk.demo.watchkitapp
        SDKROOT: watchos
        DEVELOPMENT_TEAM: 5Z3RQE949K
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: WatchDemo
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        ARCHS: arm64
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        OTHER_LDFLAGS: "$(inherited) -framework CoreMotion -lc++"
        WKCOMPANIONAPP_BUNDLE_IDENTIFIER: com.xx.xx.sdk.demo
        SWIFT_OBJC_BRIDGING_HEADER: Sources/WatchDemo-Bridging-Header.h
        HEADER_SEARCH_PATHS: "$(inherited) $(SRCROOT)/Frameworks/cpp_sdk.framework/Headers"
    scheme:
      testTargets: []
      gatherCoverageData: false
